name: Jolkenmain
version: ${project.version}
author: Jolken
main: jolkenplugins.jolkenmain.Jolkenmain
api-version: 1.14
commands:
  war:
    description: my command
    usage: /war
    aliases: w
    permission: jolken.war
  survival:
    description: my command
    usage: /survival
    aliases: sv
